version:"3.8"
services:
  web:
    depends_on:
      - api
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000

    develop:
      watch: 
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path ./frontend
          target: /app
          action: sync
    
    api:
       depends_on:
       - db
      build: ./backend
      ports:
        - "8000:8000"
      environment:
        - MONGO_URI=mongodb://mongo:27017/mern-docker
        - PORT=8000
      volumes :
        - ./backend:/app
